name: Continuous Integration Playground
run-name: ${{ github.actor }} pushed ${{ github.ref }}
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - name: cache deps
        uses: actions/cache/save@v3
        with:
          path: node_modules
          key: deps-${{ github.run_id }}

  run:
    needs: install

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: restore deps cache
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: deps-${{ github.run_id }}
      - run: npm run build && npm start
      - name: cache output
        uses: actions/cache/save@v3
        with:
          path: dist
          key: dist-${{ github.run_id }}

  verify:
    needs: run

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: restore deps cache
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: deps-${{ github.run_id }}
      - name: restore output cache
        uses: actions/cache/restore@v3
        with:
          path: dist
          key: dist-${{ github.run_id }}
      - run: npm run verify
